export enum NotifyAction {
    Caricamento = 'LOADING',
    Creazione = 'CREATION',
    Aggiornamento = 'UPDATE',
    Eliminazione = 'DELETION',
    Assegnazione = 'ASSIGNMENT',
    Rimozione = 'REMOVAL',
    Salvataggio = 'SAVE',
    AddEmployee = 'ADD_EMPLOYEE',
    AddProject = 'ADD_PROJECT',
    AddRole = 'ADD_ROLE',
    AddClient = 'ADD_CLIENT',
    UpdateEmployee = 'UPDATE_EMPLOYEE',
    UpdateProject = 'UPDATE_PROJECT',
    UpdateRole = 'UPDATE_ROLE',
    UpdateClient = 'UPDATE_CLIENT',
    UpdateWorkGroup = 'UPDATE_WORK_GROUP',
    FiltriEmployee = 'FILTER_EMPLOYEE',
    FiltriProject = 'FILTER_PROJECT',
    FiltriRole = 'FILTER_ROLE',
    FiltriClient = 'FILTER_CLIENT',
    FiltriWorkGroup = 'FILTER_WORK_GROUP',
    CampiObbligatori = 'REQUIRED_FIELDS',
    RisorseAssegnate = 'RESOURCES_ASSIGNED',
    ErroreRisorseAssegnate = 'ERROR_ASSIGNING_RESOURCES',
    ErroreCaricamento = 'ERROR_LOADING',
    Ricaricamento = 'RELOADING',
}