export const PROGETTO_COMPLETO_HEADERS = {
  company: 'Azienda',
  pm: 'PM',
  customer: 'Cliente',
  head: 'Referente',
  activity: 'Attività',
  description: 'Descrizione',
  totalBudget: 'Budget Totale',
  projectStatus: 'Stato',
  startDate: 'Data Inizio',
  endDate: 'Data Fine',
  totalDays: 'Giorni',
  winProbability: 'Win %',
  projectEmployees: 'Risorse',
  projectJobRoles: 'Ruoli',
  id: 'ID',
};
