// import { Progetto } from "./progetto/progetto.model";

// export const PROGETTI_DUMMY: Progetto[] = [
//   {
//     Id: '1',
//     Attivita: 'Sviluppo Portale Web',
//     Descrizione: 'Realizzazione portale web aziendale responsive',
//     Status: 'In Corso',
//     Cliente: 'ACME S.p.A.',
//     Referente: 'Mario Rossi',
//     Azienda: 'Tech Solutions',
//     PM: 'Laura Bianchi',
//     Giorni: 45,
//     winPercentual: 80,
//   },
//   {
//     Id: '2',
//     Attivita: 'App Mobile',
//     Descrizione: 'Sviluppo app mobile iOS e Android',
//     Status: 'Bozza',
//     Cliente: 'Beta Group',
//     Referente: 'Giulia Verdi',
//     Azienda: 'Digital Labs',
//     PM: 'Andrea Neri',
//     Giorni: 60,
//     winPercentual: 55,
//   },
//   {
//     Id: '3',
//     Attivita: 'Migrazione Cloud',
//     Descrizione: 'Migrazione infrastruttura su cloud AWS',
//     Status: 'Completato',
//     Cliente: 'Omega Corp',
//     Referente: 'Paolo Conti',
//     Azienda: 'Cloud Experts',
//     PM: 'Francesca Moretti',
//     Giorni: 30,
//     winPercentual: 100,
//   },
//   {
//     Id: '4',
//     Attivita: 'CRM Custom',
//     Descrizione: 'Personalizzazione CRM per rete vendita',
//     Status: 'In Attesa',
//     Cliente: 'Nova Retail',
//     Referente: 'Elena Ricci',
//     Azienda: 'Business IT',
//     PM: 'Marco De Luca',
//     Giorni: 20,
//     winPercentual: 40,
//   },
//   {
//     id: '5',
//     Attivita: 'Data Analysis',
//     Descrizione: 'Analisi dati e dashboard KPI',
//     Status: 'In Corso',
//     Cliente: 'FinCorp',
//     Referente: 'Stefano Lombardi',
//     Azienda: 'Analytics Pro',
//     PM: 'Chiara Romano',
//     Giorni: 25,
//     winPercentual: 70,
//   },
// ];
